// Generated by CoffeeScript 1.7.0
(function() {
  var APSelector;

  module.exports = function(artPacks) {
    return new APSelector(artPacks);
  };

  APSelector = (function() {
    function APSelector(artPacks) {
      this.artPacks = artPacks;
      this.container = document.createElement('div');
      this.refresh();
      this.artPacks.on('loadedAll', this.refresh.bind(this));
    }

    APSelector.prototype.refresh = function() {
      var node, pack, _i, _len, _ref, _results;
      while (this.container.lastChild) {
        this.container.removeChild(this.container.lastChild);
      }
      _ref = this.artPacks.packs;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        pack = _ref[_i];
        if (pack == null) {
          continue;
        }
        node = document.createElement('div');
        node.setAttribute('style', 'border: 1px solid black; -webkit-user-select: none; -moz-user-select: none; cursor: move; margin: 10px;');
        node.textContent = pack.toString();
        _results.push(this.container.appendChild(node));
      }
      return _results;
    };

    return APSelector;

  })();

}).call(this);
